packages:
  - packages/libs/*
  - packages/tests/*
  - packages/examples/*

catalog:
  "@restatedev/pubsub": 0.3.2
  "@restatedev/pubsub-client": 0.3.2
  "@restatedev/restate-sdk": 1.14.0
  "@restatedev/restate-sdk-clients": 1.14.0
  "@restatedev/restate-sdk-core": 1.14.0
  "@restatedev/restate-sdk-zod": 1.14.0
  "@types/node": ^24.7.2
  "@vercel/queue": 0.1.4
  "@workflow/core": ^4.2.4
  "@workflow/errors": ^4.1.1
  "@workflow/world": ^4.1.1
  "@workflow/ai": ^4.1.2
  typescript: ^5.9.3
  workflow: ^4.2.3
  zod: 4.3.6
