packages:
  - packages/libs/*
  - packages/tests/*
  - packages/examples/*

catalog:
  # Existing
  zod: ^4.1.11
  workflow: ^4.0.1-beta.15

  # Restate SDK (all packages use same version)
  "@restatedev/restate-sdk": 1.9.1
  "@restatedev/restate-sdk-zod": 1.9.1
  "@restatedev/restate-sdk-clients": 1.9.1
  "@restatedev/restate-sdk-core": 1.9.1

  # Workflow world
  "@workflow/world": ^4.0.1-beta.6
  "@workflow/core": ^4.0.1-beta.13
  "@workflow/errors": ^4.0.1-beta.5

  # Restate Pub/Sub
  "@restatedev/pubsub": "0.3.1"
  "@restatedev/pubsub-client": "0.3.1"

  # Vercel
  "@vercel/queue": 0.0.0-alpha.28

  # Development dependencies
  "@types/node": ^24.7.2
  typescript: ^5.9.3
